name: planlive
description: Una app para crear y compartir planes con otros usuarios.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  flutter_image_compress: ^2.4.0
  cloud_firestore: ^5.6.9
  firebase_app_check: ^0.3.2+7
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7
  firebase_analytics: ^11.5.0
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.5.0
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  flutter_google_places_hoc081098: ^2.0.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  share_plus: ^11.0.0
  in_app_update: ^4.2.3
  package_info_plus: ^8.3.0




  google_fonts: ^6.1.0
  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.12.2

  image_picker: ^1.1.2
  file_picker: ^10.2.0

  geolocator: ^14.0.1
  geocoding: ^4.0.0
  timezone: ^0.10.1


  go_router: ^15.2.0

  connectivity_plus: ^6.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
flutter_native_splash:
  color: "#4A148C"  # Fondo púrpura (Deep Purple 700)
  image: assets/images/planlive.png
  branding: assets/images/planlive.png
  branding_mode: bottom
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    image: assets/images/planlive.png
    icon_background_color: "#4A148C"
    image_dark: assets/images/planlive.png
    icon_background_color_dark: "#4A148C"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/chicho.jpg
    - assets/images/fondo_planlive.png
    - assets/images/planlive.png
    - assets/icons/planlive-icono.png
    - assets/images/curro.jpg

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/planlive.png"
  adaptive_icon_background: "#4A148C"  # color de fondo para iconos adaptativos android
  adaptive_icon_foreground: "assets/images/planlive.png"